### ISSUE TITLE
"readme" name conflicts on case-insensitive filesystems

### ISSUE THREAD

**Issue by astraw** [pypa/readme#26]
Executive summary: the package name "readme" conflicts with Python installed site-packages/README file on case-insensitive filesystems.

I am using Anaconda, pip, Python 2 and Mac OS X including its HFS case-insensitive filesystem and I think the name `readme` conflicts with the file `site-packages/README`. Here's what I see:

    $ pip install readme
    Downloading/unpacking readme
      Downloading readme-0.5.1.tar.gz
      Running setup.py egg_info for package readme

    Downloading/unpacking bleach (from readme)
      Downloading bleach-1.4.1.tar.gz
      Running setup.py egg_info for package bleach

    Requirement already satisfied (use --upgrade to upgrade): docutils in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)
    Requirement already satisfied (use --upgrade to upgrade): Pygments in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)
    Requirement already satisfied (use --upgrade to upgrade): six in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)
    Downloading/unpacking html5lib>=0.999 (from bleach->readme)
      Downloading html5lib-0.999.tar.gz (885kB): 885kB downloaded
      Running setup.py egg_info for package html5lib

    Installing collected packages: readme, bleach, html5lib
      Running setup.py install for readme
        error: could not create '/Users/straw/anaconda/lib/python2.7/site-packages/readme': File exists
        Complete output from command /Users/straw/anaconda/bin/python -c "import setuptools;__file__='/private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip-z4pFRV-record/install-record.txt --single-version-externally-managed:
        running install

    running build

    running build_py

    creating build

    creating build/lib

    creating build/lib/readme

    copying readme/__about__.py -> build/lib/readme

    copying readme/__init__.py -> build/lib/readme

    copying readme/clean.py -> build/lib/readme

    copying readme/rst.py -> build/lib/readme

    creating build/lib/readme/integration

    copying readme/integration/__init__.py -> build/lib/readme/integration

    copying readme/integration/distutils.py -> build/lib/readme/integration

    running install_lib

    creating /Users/straw/anaconda/lib/python2.7/site-packages/readme

    error: could not create '/Users/straw/anaconda/lib/python2.7/site-packages/readme': File exists

    ----------------------------------------
    Cleaning up...
    Command /Users/straw/anaconda/bin/python -c "import setuptools;__file__='/private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip-z4pFRV-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme
    Storing complete log in /Users/straw/.pip/pip.log

And indeed `/Users/straw/anaconda/lib/python2.7/site-packages/readme` does exist with the contents:

    This directory exists so that 3rd party packages can be installed
    here.  Read the source for site.py for more details.

I guess this is installed directly from the original Python source file `./Lib/site-packages/README`. Due to the case insensitivity of the file system, this causes a name clash.

Removing the original file allows pip install readme to complete successfully.

**Comment by scls19fr** [comment]
see https://github.com/mgedmin/restview/issues/30
and https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/AGHXzB1sN0I

**Comment by scls19fr** [comment]
According Ilan (from Continuum - editor of Anaconda) they didn't do anything special with README file. He suggest to rename your package. See https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/AGHXzB1sN0I

**Comment by scls19fr** [comment]
http://bugs.python.org/issue24633

**Comment by YuhanXu** [comment]
http://stackoverflow.com/questions/22121569/oserror-errno-13-permission-denied-when-updating-setuptools
